function lasers=prepare_lasers(n_lasers)

lasers(1:n_lasers)=struct(...
    'name', '', ...
    'power', [], ...
    'sequence', [], ...
    'on_during_frametime', [], ...
    'on_during_addtime', [], ...
    'accumulated_dose', 0, ...
    'mode', [], ...
    'fwhm', [], ...
    'tirf', 0, ...
    'tirf_angle', [], ...
    'tirf_amplification', [], ...
    'wavelength', [], ...
    'polarization', [], ...
    'phi', [], ...
    'frap_mode', 0 ...
    );
end
